import React from "react";
import { createRoot } from "react-dom/client";
import "@fontsource/bungee/400.css";
import "@fontsource/space-grotesk/400.css";
import "@fontsource/space-grotesk/500.css";
import "@fontsource/space-grotesk/600.css";
import "@fontsource/space-grotesk/700.css";
import { App } from "./App";
import "./style.css";
createRoot(document.getElementById("root")!).render(<App />);
